---
- hosts: centos72
  become: true
  vars:
    root_user: root
    vagrant_user: vagrant
    ruby_version: 2.2.3
    rvm_ruby_version: ruby-2.2.3
    mysql_version: 5.7
    mysql_root_password: root
    nodejs_version: v6.8.1
    dein_vim_dest: ~/Sources/Provision/Github/DeinVim
  roles:
    - railsenv
    - mysql
    - nodejs
    - vim
