---
- name: Check nodejs is already installed
  shell: node -v
  register: nodejs_installed
  failed_when: nodejs_installed.rc not in [0, 1]
  ignore_errors: True
- name: Update yum
  yum: name=* state=present
  when: nodejs_installed.rc not in [0, 1]
- name: package for node.js v6
  become: True
  shell: "curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -"
  when: nodejs_installed.rc not in [0, 1]
- name: Install nodejs
  become: True
  yum: name=nodejs
  when: nodejs_installed.rc not in [0, 1]
